const arr = [{
  country: 'Italy',
  city: 'Milan',
  price: '27461',
  url: 'https://city.travel/to/city/MXP/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/MIL.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '9.180621', '45.469436' ],
  temperature: 8,
},
{
  country: 'Serbia',
  city: 'Belgrade',
  price: '27101',
  url: 'https://city.travel/to/city/BEG/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/BEG.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '20.46046', '44.816232' ],
  temperature: 6,
},
{
  country: 'Ukraine',
  city: 'Kharkov',
  price: '27597',
  url: 'https://city.travel/to/city/HRK/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/HRK.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '36.231202', '49.992167' ],
  temperature: -6,
},
{
  country: 'Egypt',
  city: 'Cairo',
  price: '28361',
  url: 'https://city.travel/to/city/CAI/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/CAI.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '31.2469', '30.050747' ],
  temperature: 20,
},
{
  country: 'Ukraine',
  city: 'Odessa',
  price: '28382',
  url: 'https://city.travel/to/city/ODS/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/ODS.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '30.731689', '46.484207' ],
  temperature: 0,
},
{
  country: 'Croatia',
  city: 'Zagreb',
  price: '29446',
  url: 'https://city.travel/to/city/ZAG/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/ZAG.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '15.978577', '45.808594' ],
  temperature: 6,
},
{
  country: 'Armenia',
  city: 'Gyoumri',
  price: '30213',
  url: 'https://city.travel/to/city/LWN/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/LWN.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '0', '0' ],
  temperature: -1000,
},
{
  country: 'Tunisia',
  city: 'Tunis',
  price: '31121',
  url: 'https://city.travel/to/city/TUN/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/TUN.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '9.602442', '34.773985' ],
  temperature: 11,
},
{
  country: 'Romania',
  city: 'Bucharest',
  price: '32515',
  url: 'https://city.travel/to/city/OTP/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/BUH.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '26.102437', '44.428089' ],
  temperature: 2,
},
{
  country: 'Kyrgyzstan',
  city: 'Bishkek',
  price: '32577',
  url: 'https://city.travel/to/city/FRU/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/FRU.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '74.616197', '42.878645' ],
  temperature: 6,
},
{
  country: 'Kazakhstan',
  city: 'Nur-Sultan',
  price: '32977',
  url: 'https://city.travel/to/city/NQZ/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/NQZ.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '71.430411', '51.128207' ],
  temperature: -6,
},
{
  country: 'Egypt',
  city: 'Hurghada',
  price: '34267',
  url: 'https://city.travel/to/city/HRG/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/HRG.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '33.834425', '27.234275' ],
  temperature: 25,
},
{
  country: 'United States',
  city: 'New York',
  price: '34556',
  url: 'https://city.travel/to/city/JFK/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/NYC.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-74.002791', '40.714599' ],
  temperature: 8,
},
{
  country: 'Uzbekistan',
  city: 'Tashkent',
  price: '35327',
  url: 'https://city.travel/to/city/TAS/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/TAS.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '69.279737', '41.311151' ],
  temperature: 12,
},
{
  country: 'Turkey',
  city: 'Alania',
  price: '35510',
  url: 'https://city.travel/to/city/GZP/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/GZP.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '31.998754', '36.536567' ],
  temperature: 19,
},
{
  country: 'Morocco',
  city: 'Casablanca',
  price: '35919',
  url: 'https://city.travel/to/city/CMN/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/CMN.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-7.602891', '33.574018' ],
  temperature: 12,
},
{
  country: 'Bulgaria',
  city: 'Sofia',
  price: '36967',
  url: 'https://city.travel/to/city/SOF/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/SOF.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '23.314498', '42.697833' ],
  temperature: 1,
},
{
  country: 'Egypt',
  city: 'Sharm el Sheikh',
  price: '37919',
  url: 'https://city.travel/to/city/SSH/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/SSH.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '34.362329', '27.95863' ],
  temperature: 28,
},
{
  country: 'Georgia',
  city: 'Batumi',
  price: '37349',
  url: 'https://city.travel/to/city/BUS/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/BUS.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '41.636267', '41.651102' ],
  temperature: 12,
},
{
  country: 'Spain',
  city: 'Alicante',
  price: '37725',
  url: 'https://city.travel/to/city/YJE/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/YJE.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-0.485971', '38.343905' ],
  temperature: 17,
},
{
  country: 'Turkey',
  city: 'Nevsehir',
  price: '38265',
  url: 'https://city.travel/to/city/NAV/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/NAV.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '34.714532', '38.626131' ],
  temperature: 12,
},
{
  country: 'Switzerland',
  city: 'Basel',
  price: '38020',
  url: 'https://city.travel/to/city/BSL/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/BSL.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '7.606835', '47.553125' ],
  temperature: 11,
},
{
  country: 'Lithuania',
  city: 'Vilnius',
  price: '39240',
  url: 'https://city.travel/to/city/VNO/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/VNO.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '25.270894', '54.689383' ],
  temperature: -2,
},
{
  country: 'Portugal',
  city: 'Lisbon',
  price: '39329',
  url: 'https://city.travel/to/city/LIS/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/LIS.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-9.141589', '38.716174' ],
  temperature: 14,
},
{
  country: 'Uzbekistan',
  city: 'Samarkand',
  price: '40731',
  url: 'https://city.travel/to/city/SKD/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/SKD.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '66.968847', '39.654515' ],
  temperature: 11,
},
{
  country: 'Spain',
  city: 'Palma',
  price: '40252',
  url: 'https://city.travel/to/city/PMI/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/PMI.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '2.664753', '39.5676' ],
  temperature: 14,
},
{
  country: 'Azerbaijan',
  city: 'Baku',
  price: '42190',
  url: 'https://city.travel/to/city/GYD/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/BAK.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '49.853139', '40.372967' ],
  temperature: 5,
},
{
  country: 'Kazakhstan',
  city: 'Almaty',
  price: '43711',
  url: 'https://city.travel/to/city/ALA/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/ALA.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '76.945618', '43.237156' ],
  temperature: 4,
},
{
  country: 'United Arab Emirates',
  city: 'Dubai',
  price: '44105',
  url: 'https://city.travel/to/city/DXB/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/DXB.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '55.278478', '25.195137' ],
  temperature: 29,
},
{
  country: 'United States',
  city: 'San Francisco',
  price: '43203',
  url: 'https://city.travel/to/city/XXQ/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/XXQ.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-122.446904', '37.759351' ],
  temperature: 7,
},
{
  country: 'Kyrgyzstan',
  city: 'Osh',
  price: '45701',
  url: 'https://city.travel/to/city/OSS/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/OSS.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '72.80557', '40.517518' ],
  temperature: 6,
},
{
  country: 'Turkey',
  city: 'Adana',
  price: '43529',
  url: 'https://city.travel/to/city/ADA/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/ADA.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '35.319448', '37.00294' ],
  temperature: 20,
},
{
  country: 'Bosnia and Herzegovina',
  city: 'Sarajevo',
  price: '45526',
  url: 'https://city.travel/to/city/SJJ/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/SJJ.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '18.360972', '43.851241' ],
  temperature: 1,
},
{
  country: 'Turkey',
  city: 'Izmir',
  price: '46030',
  url: 'https://city.travel/to/city/ADB/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/IZM.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '27.134556', '38.428822' ],
  temperature: 11,
},
{
  country: 'Maldives',
  city: 'Male',
  price: '48605',
  url: 'https://city.travel/to/city/MLE/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/MLE.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '73.509688', '4.174972' ],
  temperature: 28,
},
{
  country: 'Canada',
  city: 'Toronto',
  price: '48745',
  url: 'https://city.travel/to/city/YYZ/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/YTO.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-79.431292', '43.684345' ],
  temperature: 15,
},
{
  country: 'Estonia',
  city: 'Tallinn',
  price: '54720',
  url: 'https://city.travel/to/city/TLL/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/TLL.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '24.743349', '59.421937' ],
  temperature: -2,
},
{
  country: 'Germany',
  city: 'Cologne',
  price: '53054',
  url: 'https://city.travel/to/city/CGN/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/CGN.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '6.938399', '50.930779' ],
  temperature: 12,
},
{
  country: 'Albania',
  city: 'Tirana',
  price: '54522',
  url: 'https://city.travel/to/city/TIA/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/TIA.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '19.820366', '41.330587' ],
  temperature: 9,
},
{
  country: 'India',
  city: 'Delhi',
  price: '55880',
  url: 'https://city.travel/to/city/DEL/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/DEL.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '77.219721', '28.632846' ],
  temperature: 33,
},
{
  country: 'Mexico',
  city: 'Cancun',
  price: '57262',
  url: 'https://city.travel/to/city/CUN/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/CUN.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-86.844882', '21.169379' ],
  temperature: 25,
},
{
  country: 'Thailand',
  city: 'Bangkok',
  price: '61799',
  url: 'https://city.travel/to/city/BKK/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/BKK.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '100.513782', '13.77137' ],
  temperature: 36,
},
{
  country: 'Dominican Republic',
  city: 'Santo Domingo',
  price: '62089',
  url: 'https://city.travel/to/city/SDQ/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/SDQ.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-69.919786', '18.479041' ],
  temperature: 22,
},
{
  country: 'United States',
  city: 'Los Angeles',
  price: '63749',
  url: 'https://city.travel/to/city/LAX/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/LAX.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-118.24613', '34.055855' ],
  temperature: 9,
},
{
  country: 'Uzbekistan',
  city: 'Urgench',
  price: '64003',
  url: 'https://city.travel/to/city/UGC/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/UGC.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '60.631377', '41.549689' ],
  temperature: 10,
},
{
  country: 'United Arab Emirates',
  city: 'Abu Dhabi',
  price: '67817',
  url: 'https://city.travel/to/city/AUH/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/AUH.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '54.356555', '24.485832' ],
  temperature: 30,
},
{
  country: 'Germany',
  city: 'Dusseldorf',
  price: '69049',
  url: 'https://city.travel/to/city/QDU/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/QDU.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '6.787428', '51.230569' ],
  temperature: 12,
},
{
  country: 'Kenya',
  city: 'Nairobi',
  price: '68554',
  url: 'https://city.travel/to/city/NBO/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/NBO.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '36.827899', '-1.272758' ],
  temperature: 27,
},
{
  country: 'South Africa',
  city: 'Johannesburg',
  price: '74167',
  url: 'https://city.travel/to/city/JNB/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/JNB.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '28.043391', '-26.206649' ],
  temperature: 28,
},
{
  country: 'Pakistan',
  city: 'Lahore',
  price: '71920',
  url: 'https://city.travel/to/city/LHE/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/LHE.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '74.303197', '31.518846' ],
  temperature: 28,
},
{
  country: 'United States',
  city: 'Miami FL',
  price: '75231',
  url: 'https://city.travel/to/city/MIA/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/MIA.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-80.250852', '25.792235' ],
  temperature: 22,
},
{
  country: 'Mexico',
  city: 'Mexico City-Toluca',
  price: '76466',
  url: 'https://city.travel/to/city/MEX/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/MEX.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-102.277714', '23.530671' ],
  temperature: 10,
},
{
  country: 'Indonesia',
  city: 'Denpasar Bali',
  price: '76836',
  url: 'https://city.travel/to/city/DPS/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/DPS.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '115.219275', '-8.682311' ],
  temperature: 30,
},
{
  country: 'Kazakhstan',
  city: 'Shimkent',
  price: '80450',
  url: 'https://city.travel/to/city/CIT/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/CIT.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '69.586907', '42.315514' ],
  temperature: 11,
},
{
  country: 'Tajikistan',
  city: 'Dushanbe',
  price: '82253',
  url: 'https://city.travel/to/city/DYU/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/DYU.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '68.779716', '38.576271' ],
  temperature: 10,
},
{
  country: 'Thailand',
  city: 'Phuket',
  price: '82877',
  url: 'https://city.travel/to/city/HKT/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/585/HKT.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '98.396857', '7.877035' ],
  temperature: 35,
},
{
  country: 'United States',
  city: 'Washington',
  price: '80780',
  url: 'https://city.travel/to/city/IAD/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/WAS.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-77.036527', '38.899513' ],
  temperature: 14,
},
{
  country: 'Tanzania',
  city: 'Zanzibar',
  price: '92136',
  url: 'https://city.travel/to/city/ZNZ/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/ZNZ.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '39.204096', '-6.165375' ],
  temperature: 31,
},
{
  country: 'United States',
  city: 'Ontario CA',
  price: '92208',
  url: 'https://city.travel/to/city/ONT/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/ONT.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '-117.612207', '34.044101' ],
  temperature: 7,
},
{
  country: 'India',
  city: 'Goa',
  price: '93110',
  url: 'https://city.travel/to/city/GOI/RT/3/0/0?from=LED',
  photoUrl: 'https://static.city.travel/spec/275/GOI.jpg',
  source: 'city-avia',
  direction: 'в обе стороны',
  persons: '1',
  isAdded: false,
  lonLat: [ '74.101094', '15.348908' ],
  temperature: 31,
},];

module.exports = arr;

