export const CHECK_USER_SESSION = "CHECK_USER_SESSION"
export const VERIFY_USER = "VERIFY_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const SET_TOURS = "SET_TOURS"
export const SET_SORTED_TOURS = "SET_SORTED_TOURS"

export const SORTED_PRICE_TOURS = 'SORTED_PRICE_TOURS'
export const SORTED_RATE_TOURS = 'SORTED_RATE_TOURS'
export const SORTED_STARS_TOURS = 'SORTED_STARS_TOURS'
export const FILTER_TOURS = 'FILTER_TOURS'

export const SET_USERS_TOURS = "SET_USERS_TOURS"
export const ADD_TOUR = "ADD_TOUR"
export const DELETE_TOUR = "DELETE_TOUR"

export const CHANGE_IS_ADDED = 'CHANGE_IS_ADDED'

export const SET_AVIA_FROM_BD = 'SET_AVIA_FROM_BD'
export const FILTER_AVIA_BY_PRICE = 'FILTER_AVIA_BY_PRICE'
export const SET_SORTED_AVIA = 'SET_SORTED_AVIA'
export const ADD_AVIA = 'ADD_AVIA'
export const DELETE_AVIA = 'DELETE_AVIA'


