export const CHECK_USER_SESSION = "CHECK_USER_SESSION"
export const VERIFY_USER = "VERIFY_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const SET_TOURS = "SET_TOURS"
export const SET_SORTED_TOURS = "SET_SORTED_TOURS"

export const SORTED_PRICE_TOURS = 'SORTED_PRICE_TOURS'
export const SET_SORTED_TOURS1 = 'SET_SORTED_TOURS1'

export const SET_USERS_TOURS = "SET_USERS_TOURS"
export const ADD_TOUR = "ADD_TOUR"
export const DELETE_TOUR = "DELETE_TOUR"

